export type Difficulty = 'Easy' | 'Medium' | 'Hard';

export type Problem = {
  id: number;
  title: string;
  difficulty: Difficulty;
  note: string;
  slug: string;
  memoryCue?: string;
};

export type Chapter = {
  id: string;
  pattern: string;
  title: string;
  shortTitle: string;
  complexity: string;
  intro: string;
  cues: string[];
  insight: string;
  templateTitle: string;
  code: string;
  problems: Problem[];
};

const p = (
  id: number,
  title: string,
  difficulty: Difficulty,
  slug: string,
  note: string,
  memoryCue?: string,
): Problem => ({
  id,
  title,
  difficulty,
  slug,
  note,
  memoryCue,
});

export const chapters: Chapter[] = [
  {
    id: 'arrays',
    pattern: '01',
    title: 'Arrays, Hashing & Prefix Sums',
    shortTitle: 'Arrays & Hashing',
    complexity: 'O(n)',
    intro:
      'Hash maps and prefix sums are the core tools for remembering what happened earlier. They replace repeated scans with a compact lookup or a reusable cumulative total.',
    cues: [
      'Frequency, duplicate, or complement lookup',
      'Subarray sum or balance condition',
      'Group by a normalized signature',
      'Need to reuse information from earlier indices',
    ],
    insight:
      'Store the smallest fact that makes the next step immediate: an index, a count, a signature, or the first position where a prefix value appeared.',
    templateTitle: 'Prefix sum + first occurrence',
    code: `first = {0: -1}\nprefix = 0\nfor i, x in enumerate(nums):\n    prefix += transform(x)\n    if prefix in first:\n        answer = max(answer, i - first[prefix])\n    else:\n        first[prefix] = i`,
    problems: [
      p(
        1,
        'Two Sum',
        'Easy',
        'two-sum',
        'The one foundational easy: check the complement before storing the value.',
      ),
      p(
        49,
        'Group Anagrams',
        'Medium',
        'group-anagrams',
        'Use a sorted word or a 26-count tuple as the hash key.',
      ),
      p(
        128,
        'Longest Consecutive Sequence',
        'Medium',
        'longest-consecutive-sequence',
        'Only grow sequences from values with no predecessor.',
      ),
      p(
        238,
        'Product of Array Except Self',
        'Medium',
        'product-of-array-except-self',
        'Combine prefix and suffix products without division.',
      ),
      p(
        36,
        'Valid Sudoku',
        'Medium',
        'valid-sudoku',
        'Track row, column, and box constraints independently.',
      ),
      p(
        560,
        'Subarray Sum Equals K',
        'Medium',
        'subarray-sum-equals-k',
        'Count earlier prefix sums equal to current minus k.',
      ),
      p(
        523,
        'Continuous Subarray Sum',
        'Medium',
        'continuous-subarray-sum',
        'Equal prefix remainders reveal a divisible subarray.',
      ),
      p(
        219,
        'Contains Duplicate II',
        'Easy',
        'contains-duplicate-ii',
        'Store the most recent index, or maintain a size-k window set.',
      ),
      p(
        380,
        'Insert Delete GetRandom O(1)',
        'Medium',
        'insert-delete-getrandom-o1',
        'Combine an array for random access with a value-to-index hash map.',
        'For O(1) deletion, swap the target with the array tail, update that index in the map, then pop.',
      ),
      p(
        41,
        'First Missing Positive',
        'Hard',
        'first-missing-positive',
        'Place each positive value at its matching array index in-place.',
        'Cyclic placement: keep swapping x into index x - 1, then scan for the first mismatch.',
      ),
    ],
  },
  {
    id: 'two-pointers',
    pattern: '02',
    title: 'Two Pointers & Sliding Windows',
    shortTitle: 'Pointers & Windows',
    complexity: 'O(n)',
    intro:
      'Two pointers shrink a pairwise search, while a sliding window maintains facts about a contiguous range. Both work because pointer movement permanently rules out possibilities.',
    cues: [
      'Sorted input and a pair or triplet target',
      'Longest or shortest valid substring',
      'Contiguous range with a frequency constraint',
      'A left boundary can repair an invalid range',
    ],
    insight:
      'For two pointers, move the side that limits improvement. For a window, expand to discover and shrink only until the invariant becomes valid again.',
    templateTitle: 'Variable sliding window',
    code: `left = 0\nfor right, x in enumerate(items):\n    add(x)\n    while window_is_invalid():\n        remove(items[left])\n        left += 1\n    answer = best(answer, right - left + 1)`,
    problems: [
      p(
        167,
        'Two Sum II — Input Array Is Sorted',
        'Medium',
        'two-sum-ii-input-array-is-sorted',
        'Move the low or high pointer according to the current sum.',
      ),
      p(
        125,
        'Valid Palindrome',
        'Easy',
        'valid-palindrome',
        'Move inward while skipping non-alphanumeric characters.',
      ),
      p(
        88,
        'Merge Sorted Array',
        'Easy',
        'merge-sorted-array',
        'Fill nums1 from the back so unread values are never overwritten.',
      ),
      p(
        27,
        'Remove Element',
        'Easy',
        'remove-element',
        'Use one pointer to scan and one to write retained values.',
      ),
      p(
        75,
        'Sort Colors',
        'Medium',
        'sort-colors',
        'Partition zeros, unknown values, and twos with three pointers.',
        'Dutch national flag: low is the next zero, mid scans, and high is the next two; recheck mid after swapping with high.',
      ),
      p(
        31,
        'Next Permutation',
        'Medium',
        'next-permutation',
        'Find the rightmost ascent, swap with the next larger suffix value, then reverse the suffix.',
        'Three steps: find the pivot from the right, swap with the rightmost larger value, then reverse everything after the pivot.',
      ),
      p(
        15,
        '3Sum',
        'Medium',
        '3sum',
        'Sort, fix one number, then run a duplicate-aware pair search.',
      ),
      p(
        11,
        'Container With Most Water',
        'Medium',
        'container-with-most-water',
        'Move the shorter wall because it limits the area.',
      ),
      p(
        42,
        'Trapping Rain Water',
        'Hard',
        'trapping-rain-water',
        'Advance the side with the smaller maximum boundary.',
        'Two pointers: the smaller side is already bounded, so its trapped water can be finalized.',
      ),
      p(
        3,
        'Longest Substring Without Repeating Characters',
        'Medium',
        'longest-substring-without-repeating-characters',
        'Jump the left edge past the previous occurrence.',
      ),
      p(
        424,
        'Longest Repeating Character Replacement',
        'Medium',
        'longest-repeating-character-replacement',
        'Window cost is length minus the most frequent character.',
      ),
      p(
        567,
        'Permutation in String',
        'Medium',
        'permutation-in-string',
        'Compare fixed-window character counts.',
      ),
      p(
        438,
        'Find All Anagrams in a String',
        'Medium',
        'find-all-anagrams-in-a-string',
        'Maintain the deficit of the fixed-size window.',
      ),
      p(
        209,
        'Minimum Size Subarray Sum',
        'Medium',
        'minimum-size-subarray-sum',
        'Shrink positive-number windows as soon as the target is reached.',
      ),
      p(
        76,
        'Minimum Window Substring',
        'Hard',
        'minimum-window-substring',
        'Track how many required character counts are fully satisfied.',
      ),
      p(
        239,
        'Sliding Window Maximum',
        'Hard',
        'sliding-window-maximum',
        'Keep useful candidates in a decreasing deque.',
        'Monotonic deque: remove smaller values from the back and expired indices from the front.',
      ),
    ],
  },
  {
    id: 'stack',
    pattern: '03',
    title: 'Stacks & Monotonic Order',
    shortTitle: 'Stacks',
    complexity: 'O(n)',
    intro:
      'A stack holds unfinished work in last-in, first-out order. A monotonic stack additionally discards items that can never influence a future answer.',
    cues: [
      'Nested pairs, decoding, or expression evaluation',
      'Next greater or smaller value',
      'Nearest boundary on either side',
      'Undo or reverse-order processing',
    ],
    insight:
      'Each index enters and leaves a monotonic stack at most once, so a loop with repeated pops is still linear overall.',
    templateTitle: 'Next greater element',
    code: `stack = []\nfor i, x in enumerate(nums):\n    while stack and nums[stack[-1]] < x:\n        j = stack.pop()\n        answer[j] = i - j\n    stack.append(i)`,
    problems: [
      p(
        20,
        'Valid Parentheses',
        'Easy',
        'valid-parentheses',
        'The only easy here: establish the matching-stack invariant.',
      ),
      p(
        155,
        'Min Stack',
        'Medium',
        'min-stack',
        'Store the running minimum beside every pushed value.',
      ),
      p(
        150,
        'Evaluate Reverse Polish Notation',
        'Medium',
        'evaluate-reverse-polish-notation',
        'Operands wait on the stack until an operator arrives.',
      ),
      p(
        394,
        'Decode String',
        'Medium',
        'decode-string',
        'Save the outer string and repeat count at every opening bracket.',
      ),
      p(
        735,
        'Asteroid Collision',
        'Medium',
        'asteroid-collision',
        'Only a right-moving stack top can collide with a new left mover.',
      ),
      p(
        739,
        'Daily Temperatures',
        'Medium',
        'daily-temperatures',
        'Keep unresolved days in decreasing temperature order.',
      ),
      p(
        503,
        'Next Greater Element II',
        'Medium',
        'next-greater-element-ii',
        'Run a decreasing stack across two passes of the circular array.',
        'Circular monotonic stack: iterate through 2n with i % n, but only push indices during the first pass.',
      ),
      p(
        402,
        'Remove K Digits',
        'Medium',
        'remove-k-digits',
        'Pop larger preceding digits while removals remain, then trim leading zeros.',
        'Greedy monotonic stack: the earliest possible decrease matters most; remove leftover digits from the end.',
      ),
      p(
        316,
        'Remove Duplicate Letters',
        'Medium',
        'remove-duplicate-letters',
        'Use last occurrence, an in-stack set, and an increasing result stack.',
        'Pop a larger letter only if it appears again later; every letter must remain exactly once.',
      ),
      p(
        901,
        'Online Stock Span',
        'Medium',
        'online-stock-span',
        'Compress dominated prices together with their spans.',
      ),
      p(
        853,
        'Car Fleet',
        'Medium',
        'car-fleet',
        'Sort by position and merge cars whose arrival time cannot overtake.',
      ),
      p(
        84,
        'Largest Rectangle in Histogram',
        'Hard',
        'largest-rectangle-in-histogram',
        'Popping reveals the first smaller boundary on the right.',
        'Increasing stack of start-index and height; when lower arrives, pop and extend its start left.',
      ),
      p(
        85,
        'Maximal Rectangle',
        'Hard',
        'maximal-rectangle',
        'Turn every matrix row into a running histogram.',
        'Convert each row to histogram heights, then reuse Largest Rectangle in Histogram exactly.',
      ),
    ],
  },
  {
    id: 'binary-search',
    pattern: '04',
    title: 'Binary Search',
    shortTitle: 'Binary Search',
    complexity: 'O(log n)',
    intro:
      'Binary search works on any monotonic answer space, not just a sorted array. Define a yes/no predicate whose answer changes at one boundary.',
    cues: [
      'Sorted or rotated values',
      'First or last valid position',
      'Minimum feasible capacity, time, or speed',
      'A condition changes from false to true once',
    ],
    insight:
      'Define the predicate first. Then decide whether the target is the first true value or the last false value and preserve that boundary invariant.',
    templateTitle: 'Find first feasible value',
    code: `lo, hi = minimum, maximum\nwhile lo < hi:\n    mid = (lo + hi) // 2\n    if feasible(mid):\n        hi = mid\n    else:\n        lo = mid + 1\nreturn lo`,
    problems: [
      p(
        704,
        'Binary Search',
        'Easy',
        'binary-search',
        'Use this once to make boundary updates automatic.',
      ),
      p(
        33,
        'Search in Rotated Sorted Array',
        'Medium',
        'search-in-rotated-sorted-array',
        'One side of the midpoint is always normally sorted.',
      ),
      p(
        153,
        'Find Minimum in Rotated Sorted Array',
        'Medium',
        'find-minimum-in-rotated-sorted-array',
        'Compare the midpoint to the right boundary.',
      ),
      p(
        34,
        'Find First and Last Position of Element',
        'Medium',
        'find-first-and-last-position-of-element-in-sorted-array',
        'Run two boundary searches instead of expanding from one match.',
      ),
      p(
        74,
        'Search a 2D Matrix',
        'Medium',
        'search-a-2d-matrix',
        'Treat the rectangular matrix as one sorted sequence.',
      ),
      p(
        875,
        'Koko Eating Bananas',
        'Medium',
        'koko-eating-bananas',
        'Search for the minimum speed that finishes on time.',
      ),
      p(
        162,
        'Find Peak Element',
        'Medium',
        'find-peak-element',
        'Compare mid with mid + 1 and keep the side that still rises toward a peak.',
        'Binary-search the slope: rising means a peak exists to the right; falling means one exists at mid or left.',
      ),
      p(
        1011,
        'Capacity To Ship Packages Within D Days',
        'Medium',
        'capacity-to-ship-packages-within-d-days',
        'Capacity is the answer space; simulation is the predicate.',
      ),
      p(
        410,
        'Split Array Largest Sum',
        'Hard',
        'split-array-largest-sum',
        'Search the smallest maximum part sum that allows enough splits.',
      ),
      p(
        4,
        'Median of Two Sorted Arrays',
        'Hard',
        'median-of-two-sorted-arrays',
        'Binary-search the partition of the smaller array.',
        'Partition the smaller array so left halves contain half the values and both cross-boundaries are ordered.',
      ),
    ],
  },
  {
    id: 'linked-lists',
    pattern: '05',
    title: 'Linked Lists & Pointer Rewiring',
    shortTitle: 'Linked Lists',
    complexity: 'O(n)',
    intro:
      'Linked-list questions are pointer choreography. Draw the links, save the next node before rewiring, and use dummy nodes when the real head may change.',
    cues: [
      'Reverse, rotate, or reorder nodes',
      'Detect a cycle or intersection',
      'Merge sorted chains',
      'Find the middle or k-th node from the end',
    ],
    insight:
      'Fast and slow pointers reveal distance relationships without extra memory. A dummy head removes most edge cases around insertion and deletion.',
    templateTitle: 'Iterative reversal',
    code: `prev, curr = None, head\nwhile curr:\n    nxt = curr.next\n    curr.next = prev\n    prev = curr\n    curr = nxt\nreturn prev`,
    problems: [
      p(
        206,
        'Reverse Linked List',
        'Easy',
        'reverse-linked-list',
        'Save next before reversing the current link.',
      ),
      p(
        141,
        'Linked List Cycle',
        'Easy',
        'linked-list-cycle',
        'A fast pointer eventually catches a slow pointer inside a cycle.',
      ),
      p(
        142,
        'Linked List Cycle II',
        'Medium',
        'linked-list-cycle-ii',
        'After fast meets slow, reset one pointer to head and advance both one step.',
        'Floyd phase two: head-to-entry distance equals meeting-point-to-entry distance around the cycle.',
      ),
      p(
        146,
        'LRU Cache',
        'Medium',
        'lru-cache',
        'Combine a hash map with a doubly linked list ordered by recency.',
        'Map gives O(1) node access; a dummy-ended doubly linked list gives O(1) removal and move-to-most-recent.',
      ),
      p(
        2,
        'Add Two Numbers',
        'Medium',
        'add-two-numbers',
        'Carry arithmetic while building a fresh result chain.',
      ),
      p(
        19,
        'Remove Nth Node From End of List',
        'Medium',
        'remove-nth-node-from-end-of-list',
        'Create a fixed gap between two pointers.',
      ),
      p(
        92,
        'Reverse Linked List II',
        'Medium',
        'reverse-linked-list-ii',
        'Reverse exactly one segment while preserving both boundary links.',
      ),
      p(
        138,
        'Copy List with Random Pointer',
        'Medium',
        'copy-list-with-random-pointer',
        'Map originals to copies or interleave copied nodes.',
      ),
      p(
        143,
        'Reorder List',
        'Medium',
        'reorder-list',
        'Find the middle, reverse the second half, then weave.',
      ),
      p(
        25,
        'Reverse Nodes in k-Group',
        'Hard',
        'reverse-nodes-in-k-group',
        'Reverse only after confirming that a full group remains.',
        'Find the k-th node first, save groupNext, reverse until it, then reconnect both boundaries.',
      ),
    ],
  },
  {
    id: 'intervals',
    pattern: '06',
    title: 'Intervals & Sweep Lines',
    shortTitle: 'Intervals',
    complexity: 'O(n log n)',
    intro:
      'Interval problems become orderly after sorting by a boundary. Then each interval only needs to be compared with the current merged range or the next event in time.',
    cues: [
      'Overlapping ranges or schedules',
      'Minimum rooms or simultaneous events',
      'Insert, merge, or remove ranges',
      'Coverage changes at start and end points',
    ],
    insight:
      'Sorting creates local structure. For overlap counts, convert intervals into start/end events; for merging, keep one current range and extend or flush it.',
    templateTitle: 'Merge sorted intervals',
    code: `intervals.sort()\nmerged = []\nfor start, end in intervals:\n    if not merged or start > merged[-1][1]:\n        merged.append([start, end])\n    else:\n        merged[-1][1] = max(merged[-1][1], end)`,
    problems: [
      p(
        57,
        'Insert Interval',
        'Medium',
        'insert-interval',
        'Emit ranges before, merge overlaps, then emit ranges after.',
      ),
      p(
        56,
        'Merge Intervals',
        'Medium',
        'merge-intervals',
        'Sort by start and maintain one active merged interval.',
      ),
      p(
        435,
        'Non-overlapping Intervals',
        'Medium',
        'non-overlapping-intervals',
        'Keep the interval that ends earliest.',
      ),
      p(
        1094,
        'Car Pooling',
        'Medium',
        'car-pooling',
        'Turn each trip into pickup and drop-off events, then scan passenger load.',
        'Difference array or sorted events: add at pickup, subtract at drop-off, and prefix-sum active passengers.',
      ),
      p(
        986,
        'Interval List Intersections',
        'Medium',
        'interval-list-intersections',
        'Advance the interval whose end is smaller.',
      ),
      p(
        2406,
        'Divide Intervals Into Minimum Number of Groups',
        'Medium',
        'divide-intervals-into-minimum-number-of-groups',
        'Maximum overlap equals the minimum number of groups.',
      ),
      p(
        1288,
        'Remove Covered Intervals',
        'Medium',
        'remove-covered-intervals',
        'Sort equal starts by longer end first.',
      ),
      p(
        1851,
        'Minimum Interval to Include Each Query',
        'Hard',
        'minimum-interval-to-include-each-query',
        'Sweep sorted queries with a heap of eligible intervals.',
        'Sort queries; push intervals whose start is eligible; pop intervals whose end is expired.',
      ),
      p(
        352,
        'Data Stream as Disjoint Intervals',
        'Hard',
        'data-stream-as-disjoint-intervals',
        'Merge the neighboring ranges touched by each new value.',
        'Maintain ordered disjoint ranges and merge only the predecessor/successor touching the new value.',
      ),
    ],
  },
  {
    id: 'trees',
    pattern: '07',
    title: 'Trees, BSTs & Recursion',
    shortTitle: 'Trees & BSTs',
    complexity: 'O(n)',
    intro:
      'Tree problems become manageable when each recursive call has one clear contract. Decide what a node receives from its parent and what it returns upward.',
    cues: [
      'Path, depth, ancestor, or subtree',
      'Level-by-level processing',
      'Ordered lookup in a BST',
      'A result must combine left and right children',
    ],
    insight:
      'DFS fits subtree answers; BFS fits distance and levels. For recursion, state the return value in one sentence before writing code.',
    templateTitle: 'Postorder recursion',
    code: `def dfs(node):\n    if not node:\n        return base_value\n    left = dfs(node.left)\n    right = dfs(node.right)\n    update_answer(left, right)\n    return value_for_parent(left, right)`,
    problems: [
      p(
        104,
        'Maximum Depth of Binary Tree',
        'Easy',
        'maximum-depth-of-binary-tree',
        'The base recursion contract: return subtree depth.',
      ),
      p(
        226,
        'Invert Binary Tree',
        'Easy',
        'invert-binary-tree',
        'Swap children and recurse; focus on the return contract.',
      ),
      p(
        102,
        'Binary Tree Level Order Traversal',
        'Medium',
        'binary-tree-level-order-traversal',
        'Snapshot the queue size at the start of each level.',
      ),
      p(
        199,
        'Binary Tree Right Side View',
        'Medium',
        'binary-tree-right-side-view',
        'Capture the last node of every BFS level.',
      ),
      p(
        98,
        'Validate Binary Search Tree',
        'Medium',
        'validate-binary-search-tree',
        'Carry strict lower and upper bounds down the tree.',
      ),
      p(
        230,
        'Kth Smallest Element in a BST',
        'Medium',
        'kth-smallest-element-in-a-bst',
        'Inorder traversal visits BST values in sorted order.',
      ),
      p(
        105,
        'Construct Binary Tree from Preorder and Inorder Traversal',
        'Medium',
        'construct-binary-tree-from-preorder-and-inorder-traversal',
        'Preorder selects roots; inorder splits subtrees.',
      ),
      p(
        236,
        'Lowest Common Ancestor of a Binary Tree',
        'Medium',
        'lowest-common-ancestor-of-a-binary-tree',
        'Return a found target or the node where two results meet.',
      ),
      p(
        1448,
        'Count Good Nodes in Binary Tree',
        'Medium',
        'count-good-nodes-in-binary-tree',
        'Carry the maximum value seen along the path.',
      ),
      p(
        124,
        'Binary Tree Maximum Path Sum',
        'Hard',
        'binary-tree-maximum-path-sum',
        'Return one branch upward but score two branches locally.',
      ),
      p(
        297,
        'Serialize and Deserialize Binary Tree',
        'Hard',
        'serialize-and-deserialize-binary-tree',
        'Preserve null markers so the tree structure is reversible.',
      ),
      p(
        968,
        'Binary Tree Cameras',
        'Hard',
        'binary-tree-cameras',
        'Use postorder states for uncovered, covered, and camera nodes.',
        'Three postorder states: needs camera, has camera, or covered; place cameras at parents of uncovered nodes.',
      ),
    ],
  },
  {
    id: 'tries',
    pattern: '08',
    title: 'Tries & String Search',
    shortTitle: 'Tries & Strings',
    complexity: 'O(word length)',
    intro:
      'A trie shares prefixes across many words. It is useful when queries explore characters incrementally or when many words must be matched against one board or stream.',
    cues: [
      'Prefix lookup or autocomplete',
      'Many dictionary words share prefixes',
      'Wildcard character search',
      'Search branches can be pruned by prefixes',
    ],
    insight:
      'A trie pays an upfront memory cost to make every prefix a navigable state. Prune dead branches aggressively during backtracking.',
    templateTitle: 'Trie insertion and lookup',
    code: `node = root\nfor char in word:\n    node = node.children.setdefault(char, Node())\nnode.is_word = True\n\n# Search follows the same edges and checks is_word.`,
    problems: [
      p(
        208,
        'Implement Trie (Prefix Tree)',
        'Medium',
        'implement-trie-prefix-tree',
        'Build the core insert, exact-search, and prefix-search operations.',
      ),
      p(
        211,
        'Design Add and Search Words Data Structure',
        'Medium',
        'design-add-and-search-words-data-structure',
        'A wildcard creates a DFS branch across all children.',
      ),
      p(
        648,
        'Replace Words',
        'Medium',
        'replace-words',
        'Stop at the shortest dictionary prefix.',
      ),
      p(
        677,
        'Map Sum Pairs',
        'Medium',
        'map-sum-pairs',
        'Maintain prefix totals while accounting for overwritten keys.',
      ),
      p(
        1268,
        'Search Suggestions System',
        'Medium',
        'search-suggestions-system',
        'Keep a small ordered suggestion list at each prefix.',
      ),
      p(
        212,
        'Word Search II',
        'Hard',
        'word-search-ii',
        'Combine board backtracking with trie prefix pruning.',
        'Build one trie for all words, DFS the board once, and delete exhausted trie branches.',
      ),
      p(
        472,
        'Concatenated Words',
        'Hard',
        'concatenated-words',
        'Use earlier words to segment each longer word.',
        'Sort words by length and test each word using only previously accepted shorter words.',
      ),
    ],
  },
  {
    id: 'heaps',
    pattern: '09',
    title: 'Heaps & Priority Queues',
    shortTitle: 'Heaps & Top K',
    complexity: 'O(n log k)',
    intro:
      'A heap keeps the next most important item available while the set changes. For top K, cap the heap so work depends on k rather than the full input size.',
    cues: [
      'K largest, closest, or most frequent',
      'Repeatedly process the next smallest event',
      'Merge sorted sources',
      'Streaming median or scheduling',
    ],
    insight:
      'Choose the heap root as the candidate you are most willing to evict. A min-heap therefore retains the largest k values.',
    templateTitle: 'Capped heap',
    code: `heap = []\nfor x in items:\n    heappush(heap, score(x))\n    if len(heap) > k:\n        heappop(heap)\n# heap contains the best k candidates`,
    problems: [
      p(
        215,
        'Kth Largest Element in an Array',
        'Medium',
        'kth-largest-element-in-an-array',
        'Maintain a min-heap capped at k values.',
      ),
      p(
        347,
        'Top K Frequent Elements',
        'Medium',
        'top-k-frequent-elements',
        'Heap frequencies or exploit bounded counts with buckets.',
      ),
      p(
        973,
        'K Closest Points to Origin',
        'Medium',
        'k-closest-points-to-origin',
        'Use squared distance and retain only k candidates.',
      ),
      p(
        621,
        'Task Scheduler',
        'Medium',
        'task-scheduler',
        'Process the most frequent available task and cool it down.',
      ),
      p(
        378,
        'Kth Smallest Element in a Sorted Matrix',
        'Medium',
        'kth-smallest-element-in-a-sorted-matrix',
        'Merge sorted rows or binary-search the value space.',
      ),
      p(
        1834,
        'Single-Threaded CPU',
        'Medium',
        'single-threaded-cpu',
        'Sweep enqueue times and heap available jobs by priority.',
      ),
      p(
        23,
        'Merge k Sorted Lists',
        'Hard',
        'merge-k-sorted-lists',
        'Keep only the current head of every nonempty list.',
      ),
      p(
        295,
        'Find Median from Data Stream',
        'Hard',
        'find-median-from-data-stream',
        'Balance a max-heap lower half and min-heap upper half.',
        'Two heaps: max-heap for the lower half, min-heap for the upper half; sizes differ by at most one.',
      ),
      p(
        767,
        'Reorganize String',
        'Medium',
        'reorganize-string',
        'Always use the most frequent character not used last.',
      ),
      p(
        502,
        'IPO',
        'Hard',
        'ipo',
        'Sweep affordable projects into a max-heap of profits.',
        'Sort by required capital; before each pick, heap every newly affordable project by maximum profit.',
      ),
    ],
  },
  {
    id: 'backtracking',
    pattern: '10',
    title: 'Backtracking & Combinatorial Search',
    shortTitle: 'Backtracking',
    complexity: 'O(branches^depth)',
    intro:
      'Backtracking explores a decision tree while maintaining a partial candidate. Make one choice, recurse, then undo it so sibling branches see clean state.',
    cues: [
      'Generate all combinations or arrangements',
      'Choose, skip, or partition',
      'Constraints invalidate partial answers early',
      'Board placement or path construction',
    ],
    insight:
      'Performance comes from pruning. Sort when it exposes duplicates or makes an impossible remainder obvious, and stop before building doomed branches.',
    templateTitle: 'Choose, recurse, undo',
    code: `def backtrack(start, path):\n    if complete(path):\n        answer.append(path.copy())\n        return\n    for i in range(start, len(items)):\n        if should_skip(i): continue\n        path.append(items[i])\n        backtrack(next_start(i), path)\n        path.pop()`,
    problems: [
      p(
        78,
        'Subsets',
        'Medium',
        'subsets',
        'At each index, include or exclude the current value.',
      ),
      p(
        90,
        'Subsets II',
        'Medium',
        'subsets-ii',
        'Sort and skip equal choices at the same tree depth.',
      ),
      p(
        46,
        'Permutations',
        'Medium',
        'permutations',
        'Track which values are already used in the current arrangement.',
      ),
      p(
        47,
        'Permutations II',
        'Medium',
        'permutations-ii',
        'Skip a duplicate unless its previous twin is already in the path.',
      ),
      p(
        39,
        'Combination Sum',
        'Medium',
        'combination-sum',
        'Reuse a candidate by recursing from its own index.',
      ),
      p(
        40,
        'Combination Sum II',
        'Medium',
        'combination-sum-ii',
        'Use each candidate once and skip same-level duplicates.',
      ),
      p(
        17,
        'Letter Combinations of a Phone Number',
        'Medium',
        'letter-combinations-of-a-phone-number',
        'Every digit contributes one branching layer.',
      ),
      p(
        79,
        'Word Search',
        'Medium',
        'word-search',
        'Mark the current cell before exploring four directions.',
      ),
      p(
        131,
        'Palindrome Partitioning',
        'Medium',
        'palindrome-partitioning',
        'Only recurse after choosing a palindromic prefix.',
      ),
      p(
        51,
        'N-Queens',
        'Hard',
        'n-queens',
        'Track blocked columns and both diagonal families.',
        'One queen per row; block column, row-col diagonal, and row+col diagonal with three sets.',
      ),
    ],
  },
  {
    id: 'graphs',
    pattern: '11',
    title: 'Graphs, Grids & Union Find',
    shortTitle: 'Graphs & Union Find',
    complexity: 'O(V + E)',
    intro:
      'Graphs model arbitrary relationships. Build or infer neighbors, track visited states, and use DFS/BFS for traversal or disjoint-set union for repeated connectivity.',
    cues: [
      'Connections, components, routes, or grids',
      'Cycle detection or prerequisite ordering',
      'Shortest path with equal edge costs',
      'Repeated connectivity queries',
    ],
    insight:
      'Grid problems are graphs in disguise. Mark visited when enqueuing to avoid duplicate work; use union-by-size and path compression for dynamic components.',
    templateTitle: 'Breadth-first search',
    code: `queue = deque([start])\nseen = {start}\nwhile queue:\n    node = queue.popleft()\n    for nxt in neighbors(node):\n        if nxt not in seen:\n            seen.add(nxt)\n            queue.append(nxt)`,
    problems: [
      p(
        200,
        'Number of Islands',
        'Medium',
        'number-of-islands',
        'Flood-fill every unvisited land component.',
      ),
      p(
        133,
        'Clone Graph',
        'Medium',
        'clone-graph',
        'Map each original node to its clone during traversal.',
      ),
      p(
        994,
        'Rotting Oranges',
        'Medium',
        'rotting-oranges',
        'Multi-source BFS processes all infection fronts together.',
      ),
      p(
        130,
        'Surrounded Regions',
        'Medium',
        'surrounded-regions',
        'Protect border-connected regions before flipping the rest.',
      ),
      p(
        417,
        'Pacific Atlantic Water Flow',
        'Medium',
        'pacific-atlantic-water-flow',
        'Reverse the flow and search inward from both oceans.',
      ),
      p(
        207,
        'Course Schedule',
        'Medium',
        'course-schedule',
        'A valid schedule exists exactly when the dependency graph is acyclic.',
      ),
      p(
        210,
        'Course Schedule II',
        'Medium',
        'course-schedule-ii',
        'Return the topological order, not just cycle status.',
      ),
      p(
        684,
        'Redundant Connection',
        'Medium',
        'redundant-connection',
        'The first edge joining an existing component closes a cycle.',
      ),
      p(
        721,
        'Accounts Merge',
        'Medium',
        'accounts-merge',
        'Union accounts that share any email address.',
      ),
      p(
        547,
        'Number of Provinces',
        'Medium',
        'number-of-provinces',
        'Count connected components in an adjacency matrix.',
      ),
      p(
        399,
        'Evaluate Division',
        'Medium',
        'evaluate-division',
        'Traverse a weighted graph while multiplying edge ratios.',
      ),
      p(
        127,
        'Word Ladder',
        'Hard',
        'word-ladder',
        'BFS transformation layers; generate neighbors efficiently.',
        'Bidirectional BFS or wildcard-pattern buckets prevent scanning the whole dictionary per word.',
      ),
    ],
  },
  {
    id: 'advanced-graphs',
    pattern: '12',
    title: 'Advanced Graph Algorithms',
    shortTitle: 'Advanced Graphs',
    complexity: 'O(E log V)',
    intro:
      'Weighted paths, minimum spanning trees, and constrained routes require stronger invariants than ordinary traversal. Match the edge properties to the algorithm.',
    cues: [
      'Weighted shortest path',
      'Connect every node at minimum total cost',
      'Reconstruct an Eulerian route',
      'Shortest path with a limited number of stops',
    ],
    insight:
      'Dijkstra needs nonnegative weights; Bellman-Ford tolerates negative edges; Kruskal grows a minimum spanning tree; Hierholzer consumes every edge exactly once.',
    templateTitle: 'Dijkstra shortest path',
    code: `heap = [(0, source)]\ndist = {}\nwhile heap:\n    cost, node = heappop(heap)\n    if node in dist: continue\n    dist[node] = cost\n    for nxt, weight in graph[node]:\n        if nxt not in dist:\n            heappush(heap, (cost + weight, nxt))`,
    problems: [
      p(
        743,
        'Network Delay Time',
        'Medium',
        'network-delay-time',
        'Dijkstra finalizes nodes in increasing shortest distance.',
      ),
      p(
        1631,
        'Path With Minimum Effort',
        'Medium',
        'path-with-minimum-effort',
        'Path cost is the maximum edge; minimize it with Dijkstra.',
      ),
      p(
        1584,
        'Min Cost to Connect All Points',
        'Medium',
        'min-cost-to-connect-all-points',
        'Build a minimum spanning tree with Prim or Kruskal.',
      ),
      p(
        787,
        'Cheapest Flights Within K Stops',
        'Medium',
        'cheapest-flights-within-k-stops',
        'Distance state must include how many edges were used.',
      ),
      p(
        1976,
        'Number of Ways to Arrive at Destination',
        'Medium',
        'number-of-ways-to-arrive-at-destination',
        'Count equal-cost relaxations during Dijkstra.',
      ),
      p(
        1514,
        'Path with Maximum Probability',
        'Medium',
        'path-with-maximum-probability',
        'Use a max-heap and multiply probabilities along edges.',
      ),
      p(
        778,
        'Swim in Rising Water',
        'Hard',
        'swim-in-rising-water',
        'The path cost is the maximum elevation encountered.',
      ),
      p(
        332,
        'Reconstruct Itinerary',
        'Hard',
        'reconstruct-itinerary',
        'Hierholzer traversal builds the route in reverse.',
      ),
      p(
        269,
        'Alien Dictionary',
        'Hard',
        'alien-dictionary',
        'Derive the first differing character edge, then topologically sort.',
        'Only the first differing character gives an edge; reject the invalid longer-prefix-before-shorter case.',
      ),
      p(
        1192,
        'Critical Connections in a Network',
        'Hard',
        'critical-connections-in-a-network',
        'Low-link values identify edges with no back-route.',
        'Tarjan bridge rule: edge u-v is critical when low[v] is greater than discovery[u].',
      ),
    ],
  },
  {
    id: 'greedy',
    pattern: '13',
    title: 'Greedy Algorithms',
    shortTitle: 'Greedy',
    complexity: 'Usually O(n log n)',
    intro:
      'A greedy algorithm commits to a locally best move that can be proven not to block an optimal result. Sorting often exposes the safe exchange argument.',
    cues: [
      'Maximize reach or minimize removals',
      'Choose non-overlapping work',
      'Local surplus can cover future deficit',
      'An exchange argument can replace any optimal first move',
    ],
    insight:
      'Do not trust a greedy hunch without an invariant. Explain why any optimal solution can be changed to make your choice first without becoming worse.',
    templateTitle: 'Farthest reachable position',
    code: `farthest = 0\nfor i, jump in enumerate(nums):\n    if i > farthest:\n        return False\n    farthest = max(farthest, i + jump)\nreturn True`,
    problems: [
      p(
        55,
        'Jump Game',
        'Medium',
        'jump-game',
        'Maintain the farthest index reachable so far.',
      ),
      p(
        45,
        'Jump Game II',
        'Medium',
        'jump-game-ii',
        'Each jump expands a BFS-like reachable layer.',
      ),
      p(
        53,
        'Maximum Subarray',
        'Medium',
        'maximum-subarray',
        'Discard a negative prefix because it can only hurt the future.',
      ),
      p(
        134,
        'Gas Station',
        'Medium',
        'gas-station',
        'A failed start invalidates every station before the failure point.',
      ),
      p(
        763,
        'Partition Labels',
        'Medium',
        'partition-labels',
        'Close a partition only after every seen character ends.',
      ),
      p(
        678,
        'Valid Parenthesis String',
        'Medium',
        'valid-parenthesis-string',
        'Track the minimum and maximum possible number of opens.',
      ),
      p(
        1899,
        'Merge Triplets to Form Target Triplet',
        'Medium',
        'merge-triplets-to-form-target-triplet',
        'Ignore overshooting triplets; collect matched target coordinates.',
      ),
      p(
        846,
        'Hand of Straights',
        'Medium',
        'hand-of-straights',
        'Always start groups from the smallest remaining card.',
      ),
      p(
        135,
        'Candy',
        'Hard',
        'candy',
        'Satisfy increasing constraints from both directions.',
        'Two passes: satisfy left-neighbor increases, then right-neighbor increases using max.',
      ),
    ],
  },
  {
    id: 'dp-1d',
    pattern: '14',
    title: 'One-Dimensional Dynamic Programming',
    shortTitle: '1D Dynamic Programming',
    complexity: 'O(states × choices)',
    intro:
      'Dynamic programming stores answers to overlapping subproblems. In one dimension, a position, amount, or remaining prefix is usually enough to define the state.',
    cues: [
      'Count ways or find an optimum',
      'Choices revisit the same remainder',
      'A decision depends on a few earlier positions',
      'Greedy choices cannot be proven safe',
    ],
    insight:
      'The recurrence is the solution; the array is only storage. State the subproblem in words, write transitions, set base cases, then compress memory if possible.',
    templateTitle: 'Memoized decisions',
    code: `@cache\ndef dp(i):\n    if i >= len(items):\n        return base_case\n    skip = dp(i + 1)\n    take = value(i) + dp(next_index(i))\n    return best(skip, take)`,
    problems: [
      p(
        70,
        'Climbing Stairs',
        'Easy',
        'climbing-stairs',
        'The single DP warm-up: ways(i) comes from the previous two states.',
      ),
      p(
        198,
        'House Robber',
        'Medium',
        'house-robber',
        'Choose take-plus-two-back or skip.',
      ),
      p(
        213,
        'House Robber II',
        'Medium',
        'house-robber-ii',
        'Break the cycle into two linear robberies.',
      ),
      p(
        322,
        'Coin Change',
        'Medium',
        'coin-change',
        'Build the minimum coin count for every smaller amount.',
      ),
      p(
        139,
        'Word Break',
        'Medium',
        'word-break',
        'A position is reachable if a valid dictionary word ends there.',
      ),
      p(
        91,
        'Decode Ways',
        'Medium',
        'decode-ways',
        'Transitions depend on valid one- and two-digit decodings.',
      ),
      p(
        377,
        'Combination Sum IV',
        'Medium',
        'combination-sum-iv',
        'Order matters, so iterate choices inside every target state.',
      ),
      p(
        300,
        'Longest Increasing Subsequence',
        'Medium',
        'longest-increasing-subsequence',
        'Learn both quadratic DP and patience-sorting tails.',
        'Tails array + lower_bound: tails[length-1] is the smallest ending value for that length.',
      ),
      p(
        152,
        'Maximum Product Subarray',
        'Medium',
        'maximum-product-subarray',
        'Track both maximum and minimum products because negatives swap roles.',
      ),
      p(
        309,
        'Best Time to Buy and Sell Stock with Cooldown',
        'Medium',
        'best-time-to-buy-and-sell-stock-with-cooldown',
        'Model hold, sold, and resting states.',
      ),
      p(
        1235,
        'Maximum Profit in Job Scheduling',
        'Hard',
        'maximum-profit-in-job-scheduling',
        'Sort jobs and binary-search the next compatible state.',
        'Weighted interval scheduling: sort by start, then DP chooses skip or profit plus next compatible job.',
      ),
    ],
  },
  {
    id: 'dp-2d',
    pattern: '15',
    title: 'Two-Dimensional Dynamic Programming',
    shortTitle: '2D Dynamic Programming',
    complexity: 'O(rows × columns)',
    intro:
      'Two-dimensional DP appears when a subproblem needs two coordinates: two string positions, a grid cell, or an item index plus remaining capacity.',
    cues: [
      'Compare or transform two strings',
      'Grid paths with costs or obstacles',
      'Choose items under a capacity',
      'A state needs two independent coordinates',
    ],
    insight:
      'Draw the state grid and label what one cell means. Every transition should come from already-solved neighboring states or a smaller pair of indices.',
    templateTitle: 'Two-sequence DP',
    code: `dp = [[0] * (m + 1) for _ in range(n + 1)]\nfor i in range(n - 1, -1, -1):\n    for j in range(m - 1, -1, -1):\n        if a[i] == b[j]:\n            dp[i][j] = 1 + dp[i + 1][j + 1]\n        else:\n            dp[i][j] = best(dp[i + 1][j], dp[i][j + 1])`,
    problems: [
      p(
        62,
        'Unique Paths',
        'Medium',
        'unique-paths',
        'Every cell receives paths from above and left.',
      ),
      p(
        63,
        'Unique Paths II',
        'Medium',
        'unique-paths-ii',
        'Obstacles zero out otherwise identical grid transitions.',
      ),
      p(
        64,
        'Minimum Path Sum',
        'Medium',
        'minimum-path-sum',
        'Accumulate the cheaper predecessor into each cell.',
      ),
      p(
        5,
        'Longest Palindromic Substring',
        'Medium',
        'longest-palindromic-substring',
        'Expand centers or fill intervals from short to long.',
      ),
      p(
        1143,
        'Longest Common Subsequence',
        'Medium',
        'longest-common-subsequence',
        'State is a pair of positions in the two strings.',
      ),
      p(
        516,
        'Longest Palindromic Subsequence',
        'Medium',
        'longest-palindromic-subsequence',
        'Match endpoints or drop one endpoint.',
      ),
      p(
        494,
        'Target Sum',
        'Medium',
        'target-sum',
        'Convert signs into a subset-sum count or memoize index and total.',
      ),
      p(
        115,
        'Distinct Subsequences',
        'Hard',
        'distinct-subsequences',
        'Count ways a suffix of the source can form a suffix of the target.',
      ),
      p(
        312,
        'Burst Balloons',
        'Hard',
        'burst-balloons',
        'Choose the final balloon popped inside each interval.',
        'Interval DP becomes clean only when you choose which balloon is popped last, not first.',
      ),
      p(
        72,
        'Edit Distance',
        'Hard',
        'edit-distance',
        'Insert, delete, and replace move through neighboring states.',
      ),
      p(
        10,
        'Regular Expression Matching',
        'Hard',
        'regular-expression-matching',
        'A star either skips its pair or consumes one matching character.',
        'Memoize (string index, pattern index); star means skip x* or consume one match and stay.',
      ),
    ],
  },
  {
    id: 'bit-math',
    pattern: '16',
    title: 'Bit Manipulation, Math & Geometry',
    shortTitle: 'Bits, Math & Geometry',
    complexity: 'Varies',
    intro:
      'Bitwise structure can compress a set of boolean facts into one integer. Mathematical invariants and coordinate reasoning often remove simulation entirely.',
    cues: [
      'Parity, powers of two, or unique values',
      'Need constant-space set-like state',
      'Integer overflow or digit operations',
      'Points, slopes, rotation, or geometric counting',
    ],
    insight:
      'Know the identities: x xor x is zero, x & (x - 1) removes the lowest set bit, and shifts multiply or divide by powers of two.',
    templateTitle: 'Iterate set bits',
    code: `count = 0\nwhile value:\n    value &= value - 1  # remove lowest set bit\n    count += 1\n\n# XOR cancels paired values: a ^ a == 0`,
    problems: [
      p(
        191,
        'Number of 1 Bits',
        'Easy',
        'number-of-1-bits',
        'The one bitwise warm-up: repeatedly remove the lowest set bit.',
      ),
      p(
        338,
        'Counting Bits',
        'Easy',
        'counting-bits',
        'Reuse the count of a smaller value after removing one set bit.',
      ),
      p(
        268,
        'Missing Number',
        'Medium',
        'missing-number',
        'XOR indices and values so every paired number cancels.',
      ),
      p(
        371,
        'Sum of Two Integers',
        'Medium',
        'sum-of-two-integers',
        'XOR computes partial sum; AND and shift compute carry.',
      ),
      p(
        201,
        'Bitwise AND of Numbers Range',
        'Medium',
        'bitwise-and-of-numbers-range',
        'Only the common binary prefix survives the entire range.',
      ),
      p(
        7,
        'Reverse Integer',
        'Medium',
        'reverse-integer',
        'Build the reversed value while checking 32-bit bounds.',
      ),
      p(
        50,
        'Pow(x, n)',
        'Medium',
        'powx-n',
        'Binary exponentiation squares the base while halving the exponent.',
      ),
      p(
        43,
        'Multiply Strings',
        'Medium',
        'multiply-strings',
        'Accumulate digit-pair products into positional buckets.',
      ),
      p(
        149,
        'Max Points on a Line',
        'Hard',
        'max-points-on-a-line',
        'Normalize slopes with reduced integer direction pairs.',
        'Anchor each point and hash reduced (dy/gcd, dx/gcd) pairs; normalize signs and verticals.',
      ),
    ],
  },
];

export const totalProblemCount = chapters.reduce(
  (sum, chapter) => sum + chapter.problems.length,
  0,
);

export const difficultyTotals = chapters.reduce(
  (totals, chapter) => {
    for (const problem of chapter.problems) totals[problem.difficulty] += 1;
    return totals;
  },
  { Easy: 0, Medium: 0, Hard: 0 } as Record<Difficulty, number>,
);
